language: cpp

os: linux

dist: bionic

compiler:
  - clang
  - gcc

install:
  - sudo apt-get -y install freeglut3-dev libglew-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

script:
  - mkdir build && cd build
  - cmake .. -DLIBPX_EDITOR=ON -DLIBPX_CMD=ON
  - make
